In [213]:
import pandas as pd

In [215]:
df = pd.read_csv('../Downloads/Crop_Recommendation.csv')

In [217]:
df

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall,Crop
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Rice
...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,Coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,Coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,Coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,Coffee
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,Coffee

In [219]:
df['Crop'].value_counts()

Crop
Rice           100
Maize          100
Jute           100
Cotton         100
Coconut        100
Papaya         100
Orange         100
Apple          100
Muskmelon      100
Watermelon     100
Grapes         100
Mango          100
Banana         100
Pomegranate    100
Lentil         100
Blackgram      100
MungBean       100
MothBeans      100
PigeonPeas     100
KidneyBeans    100
ChickPea       100
Coffee         100
Name: count, dtype: int64

In [221]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nitrogen     2200 non-null   int64
 1   Phosphorus   2200 non-null   int64
 2   Potassium    2200 non-null   int64
 3   Temperature  2200 non-null   float64
 4   Humidity     2200 non-null   float64
 5   pH_Value     2200 non-null   float64
 6   Rainfall     2200 non-null   float64
 7   Crop         2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [223]:
df.describe()

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [225]:
df.isnull().sum()

Nitrogen       0
Phosphorus     0
Potassium      0
Temperature    0
Humidity       0
pH_Value       0
Rainfall       0
Crop           0
dtype: int64

In [227]:
from sklearn.preprocessing import LabelEncoder

In [229]:
le = LabelEncoder()
df['Crop'] = le.fit_transform(df['Crop'])

In [231]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nitrogen     2200 non-null   int64
 1   Phosphorus   2200 non-null   int64
 2   Potassium    2200 non-null   int64
 3   Temperature  2200 non-null   float64
 4   Humidity     2200 non-null   float64
 5   pH_Value     2200 non-null   float64
 6   Rainfall     2200 non-null   float64
 7   Crop         2200 non-null   int64
dtypes: float64(4), int64(4)
memory usage: 137.6 KB

In [233]:
x = df.drop('Crop',axis = 1)
x

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall
0,90,42,43,20.879744,82.002744,6.502985,202.935536
1,85,58,41,21.770462,80.319644,7.038096,226.655537
2,60,55,44,23.004459,82.320763,7.840207,263.964248
3,74,35,40,26.491096,80.158363,6.980401,242.864034
4,78,42,42,20.130175,81.604873,7.628473,262.717340
...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507
2196,99,15,27,27.417112,56.636362,6.086922,127.924610
2197,118,33,30,24.131797,67.225123,6.362608,173.322839
2198,117,32,34,26.272418,52.127394,6.758793,127.175293
2199,104,18,30,23.603016,60.396475,6.779833,140.937041

In [235]:
y = df['Crop']
y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: Crop, Length: 2200, dtype: int64

In [237]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [239]:
x = scaler.fit_transform(x)

In [241]:
from sklearn.model_selection import train_test_split

In [243]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [245]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [247]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [249]:
lr_pred = lr.predict(x_test)

In [251]:
lr_pred

array([21, 10,  7,  4, 16, 19,  4, 15,  8, 20,  9, 17,  1, 20, 14,  0, 19,
       19, 11, 16, 11,  5, 16,  1,  2,  7,  3,  9,  6, 12,  4, 12, 19, 14,
        5,  0,  9,  9, 16,  2,  8, 12, 19,  3,  1, 10, 18, 16,  7,  0, 18,
       14,  4, 19, 19, 15,  5,  4, 11, 12,  3,  7, 13, 20, 20, 14, 13,  5,
       20,  9, 18, 16,  4,  7,  0, 10,  3, 15,  4,  6, 11, 13, 16,  9,  6,
        5,  0,  2, 12, 19, 15,  8, 15, 16,  0, 12, 15, 10, 16, 15,  2, 12,
        6,  5, 14,  1, 10, 13,  9,  2, 10,  6, 10, 16,  6,  3,  0, 15, 19,
        7, 17, 21,  1, 18,  6, 16,  8,  0, 20,  9,  1, 15, 12,  6, 19,  4,
        9, 19, 13,  9, 17,  4, 15,  2, 14, 15, 14,  2,  4,  5,  5, 17, 16,
        7,  7,  2,  8, 15,  0, 18,  0,  5, 11, 11, 13, 11, 13, 14, 13,  7,
       13, 15,  5,  2, 19, 21, 13, 13, 13,  6, 18, 15, 21,  5, 18,  1,  1,
       11, 12,  2, 16,  9,  7,  4, 21, 19, 18, 20,  1, 11, 14,  2,  6,  1,
        0, 19, 16,  7, 19,  9,  7, 11, 17,  4, 13, 12, 11, 17,  6, 20,  5,
        8, 10,  5,  8, 13,  4,  8, 18, 12,  4,  7, 10,  7, 10,  6, 18,  4,
       17, 12, 19,  3, 19,  0, 15,  3, 16,  9, 17,  4, 15, 10,  5, 14, 16,
        9,  4,  6, 15,  5, 10, 19,  5,  9,  4,  4,  2,  7,  2, 16,  7, 15,
        6,  5, 11,  5, 18,  2, 11,  5,  8,  0,  7,  7,  6,  2, 13,  7, 21,
       14, 14, 17, 11, 16, 21, 12, 18, 16, 14,  0,  2,  9, 15,  8,  0,  8,
        9, 16,  4, 21,  8, 11,  2, 13, 20,  7, 17,  9,  8,  0, 12,  7, 14,
       14, 15,  3,  3, 10,  8,  0,  2, 12, 10, 15, 13, 18,  6, 15,  4, 18,
       16, 21,  5, 11,  1, 19,  1, 15, 12,  5, 17,  9,  5, 13,  9, 17,  2,
       13, 20, 11,  7, 15,  5,  4,  2, 11,  1, 19,  9, 16,  5, 11, 10,  1,
       12,  0,  9, 21,  5, 14, 16, 13, 14,  6, 11, 14,  3, 18, 21, 17, 12,
        1,  2,  6,  0,  6,  6, 21,  4,  7, 18, 18, 11, 21, 19,  1, 13, 17,
        2, 16, 13, 13,  3, 20,  7, 20,  5,  5,  9,  7,  2, 10,  5, 21, 17,
       17,  8, 16, 19,  8, 19,  2, 18,  4,  4,  1, 19,  2, 20, 11])

In [253]:
print("Accuracy:", accuracy_score(y_test, lr_pred))

Accuracy: 0.9704545454545455

In [255]:
print("\nClassification Report:\n", classification_report(y_test, lr_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        17
           2       0.96      1.00      0.98        24
           3       1.00      1.00      1.00        11
           4       0.96      1.00      0.98        24
           5       0.96      1.00      0.98        27
           6       1.00      0.95      0.98        21
           7       1.00      1.00      1.00        25
           8       0.62      0.77      0.69        13
           9       0.96      1.00      0.98        22
          10       1.00      1.00      1.00        16
          11       0.95      1.00      0.98        21
          12       1.00      1.00      1.00        18
          13       1.00      1.00      1.00        23
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        24
          16       1.00      0.96      0.98        26
          17       1.00      0.94      0.97        17
          18       1.00      0.90      0.95        20
          19       1.00      1.00      1.00        24
          20       0.85      0.69      0.76        16
          21       1.00      1.00      1.00        14

    accuracy                           0.97       440
   macro avg       0.97      0.96      0.96       440
weighted avg       0.97      0.97      0.97       440

In [257]:
from sklearn.naive_bayes import GaussianNB

In [259]:
nb_model = GaussianNB()
nb_model.fit(x_train, y_train)

GaussianNB()

In [261]:
nb_pred = nb_model.predict(x_test)
nb_pred

array([21, 10,  7,  4, 16, 19,  4, 15,  8, 20,  9, 17,  1, 20, 14,  0, 19,
       19, 11, 16, 11,  5, 16,  1,  2,  7,  3,  9,  6, 12, 16, 12, 19, 14,
        5,  0,  9,  9, 16,  2,  8, 12, 19,  3,  1, 10, 18, 16,  7,  0, 18,
       14,  4, 19, 19, 15,  5,  4, 11, 12,  3,  7, 13, 20, 20, 14, 13,  5,
       20,  9, 18, 16,  4,  7,  0, 10,  3, 15,  4,  6, 11, 13, 16,  9,  6,
        5,  0,  2, 12, 19, 15,  8, 15, 16,  0, 12, 15, 10, 16, 15,  2, 12,
        6,  5, 14,  1, 10, 13,  9,  2, 10,  6, 10, 16,  6,  3,  0, 15, 19,
        7, 17, 21,  1, 18,  6, 16, 20,  0, 20,  9,  1, 15, 12,  6, 19,  4,
        9, 19, 13,  9, 17,  4, 15,  2, 14, 15, 14,  2,  4,  5,  5, 17, 16,
        7,  7, 18,  8, 15,  0, 18,  0,  5, 11, 11, 13, 11, 13, 14, 13,  7,
       13, 15,  5,  2, 19, 21, 13, 13, 13,  6, 18, 15, 21,  5, 18,  1,  1,
       11, 12,  2, 16,  9,  7,  4, 21, 19, 18,  8,  1, 11, 14,  2,  6,  1,
        0, 19, 16,  7, 19,  9,  7, 11, 17,  4, 13, 12, 11, 17,  6, 20,  5,
       17, 10,  5,  8, 13,  4,  8, 18, 12,  4,  7, 10,  7, 10,  6, 18,  4,
       17, 12, 19,  3, 19,  0, 15,  3, 16,  9, 17,  4, 15, 10,  5, 14, 16,
        9,  4,  6, 15,  8, 10, 19,  5,  9,  4,  4,  2,  7,  2, 16,  7, 15,
        6,  5, 11,  5, 18,  2, 11,  5,  8,  0,  7,  7,  6,  2, 13,  7, 21,
       14, 14, 17, 11, 16, 21, 12, 18, 16, 14,  0,  2,  9, 15,  8,  0,  8,
        9, 16,  4, 21,  8, 11,  2, 13, 20,  7, 17,  9,  8,  0, 12,  7, 14,
       14, 15,  3,  3, 10, 20,  0,  2, 12, 10, 15, 13, 18,  6, 15,  4, 18,
       16, 21,  5, 11,  1, 19,  1, 15, 12,  5, 17,  9,  5, 13, 18, 17,  2,
       13, 20,  6,  7, 15,  5,  4,  2, 11,  1, 19,  9, 16,  5, 11, 10,  1,
       12,  0,  9, 21,  5, 14, 16, 13, 14,  6, 11, 14,  3, 18, 21, 17, 12,
        1,  2,  6,  0,  6,  6, 21,  4,  7, 18, 18, 11, 21, 19,  1, 13, 17,
        2, 16, 13, 13,  3, 20,  7,  8,  5,  5,  9,  7,  2, 10,  5, 21, 17,
       17,  8, 16, 19,  8, 19,  2, 18,  4,  4,  1, 19,  2, 20, 11])

In [263]:
print("Accuracy:", accuracy_score(y_test, nb_pred))

Accuracy: 0.9931818181818182

In [265]:
print("\nClassification Report:\n", classification_report(y_test, nb_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        24
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00        27
           6       1.00      1.00      1.00        21
           7       1.00      1.00      1.00        25
           8       0.81      1.00      0.90        13
           9       1.00      1.00      1.00        22
          10       1.00      1.00      1.00        16
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        18
          13       1.00      1.00      1.00        23
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        24
          16       1.00      1.00      1.00        26
          17       1.00      1.00      1.00        17
          18       1.00      1.00      1.00        20
          19       1.00      1.00      1.00        24
          20       1.00      0.81      0.90        16
          21       1.00      1.00      1.00        14

    accuracy                           0.99       440
   macro avg       0.99      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440

In [267]:
from sklearn.svm import SVC

In [269]:
svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(x_train, y_train)

SVC(random_state=42)

In [271]:
svm_pred = svm_model.predict(x_test)

In [273]:
print("Accuracy:", accuracy_score(y_test, svm_pred))

Accuracy: 0.9772727272727273

In [275]:
print("\nClassification Report:\n", classification_report(y_test, svm_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        17
           2       0.96      1.00      0.98        24
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        24
           5       0.96      1.00      0.98        27
           6       1.00      1.00      1.00        21
           7       1.00      1.00      1.00        25
           8       0.65      0.85      0.73        13
           9       1.00      1.00      1.00        22
          10       0.94      1.00      0.97        16
          11       1.00      1.00      1.00        21
          12       1.00      1.00      1.00        18
          13       1.00      0.96      0.98        23
          14       1.00      1.00      1.00        18
          15       1.00      1.00      1.00        24
          16       1.00      1.00      1.00        26
          17       1.00      0.94      0.97        17
          18       1.00      0.95      0.97        20
          19       1.00      1.00      1.00        24
          20       0.92      0.69      0.79        16
          21       1.00      1.00      1.00        14

    accuracy                           0.98       440
   macro avg       0.97      0.97      0.97       440
weighted avg       0.98      0.98      0.98       440

In [281]:
import pandas as pd

# Example: real-time input (replace values with your own)
new_data = pd.DataFrame({
    'Nitrogen': [90],
    'Phosphorus': [42],
    'Potassium': [43],
    'Temperature': [25],
    'Humidity': [80],
    'pH_Value': [6.5],
    'Rainfall': [200]
})

# Scale the new data using the same StandardScaler used during training
new_data_scaled = scaler.transform(new_data)

# Predict the crop using your trained model
predicted_crop_encoded = lr.predict(new_data_scaled)

# If you used LabelEncoder for target, convert back to original crop name
predicted_crop = le.inverse_transform(predicted_crop_encoded)

print("Recommended crop:", predicted_crop[0])

Recommended crop: Rice